name: Deploy

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Configurar SSH com agent
        run: |
          eval "$(ssh-agent -s)"

          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-add ~/.ssh/id_rsa <<< "${{ secrets.SSH_PASSPHRASE }}"

          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

          ssh ubuntu@${{ secrets.SSH_HOST }} << 'EOF'
            cd humix-new-backend

            git fetch origin
            git checkout main
            git reset --hard origin/main

            echo "Código atualizado!"
          EOF

